### ISSUE TITLE
Editable Version?

### ISSUE THREAD

**Issue by Eudox67** [t-edson/La-Biblia-del-Synedit#1]
Is there an editable version of this document, like .odt or .docx?  This way I can get translations of the text and put them into the document. Or if there is already an English version, a pointer to that would be even better. Thank you.

**Comment by t-edson** [comment]
Hi. I've included a *.doc version of the document. I don't have an English version. I remember someone was translating it to English, however, I don't have news about that.

**Comment by Eudox67** [comment]
Thanks.
