### ISSUE TITLE
A German version is available

### ISSUE THREAD

**Issue by wennerer** [t-edson/La-Biblia-del-Synedit#3]
A German version is available:
[Die Synedit Bibel.pdf.zip](https://github.com/t-edson/La-Biblia-del-Synedit/files/14622502/Die.Synedit.Bibel.pdf.zip)

**Comment by t-edson** [comment]
Thanks for the translation. Document is included in the repository.

**Comment by wennerer** [comment]
I will advertise it a little in the German Lazarus Forum.
Saludos 
Bernd
